### ISSUE TITLE
Use of propagate

### ISSUE THREAD

**Issue by markNZed** [gilad-rubin/modular-rag#2]
In the HYpster documentation https://gilad-rubin.github.io/hypster/advanced_usage/propagate.html it seems propagate should be used like:
```
my_config = hypster.load("my_config.py")
my_conf = hp.propagate(my_config)
```

Not like: https://github.com/gilad-rubin/modular-rag/blob/b1f479d6dc21cc3dc6d5b76bbf09f93073838bc9/notebooks/modular-rag.ipynb#L219

That seems to be working but probably due to a side effect of using a notebook - trying to get this code into distinct Python files raised these problems.

**Comment by gilad-rubin** [comment]
Thanks for raising this issue. Hypster has been through a lot of changes in the past two weeks and some of the core API has changed along with the documentation site. 

Please refer to the most updated documentation:
https://gilad-rubin.gitbook.io/hypster/in-depth/hp-call-types/propagate

 Bottom line is - both methods work, and I personally believe that using the path directly is a bit smoother.
